### PR TITLE
La/makie issues

### PR DESCRIPTION
**Pull request by lazarusA**
this should close https://github.com/JuliaDataScience/JuliaDataScience/issues/345

### CODE REVIEW

**Comment by rikhuijzer** [comment]
Thanks!

**Comment by rikhuijzer** [comment]
I couldn't test locally. You fixed the front page indeed 🥳 🥳 

The cheat sheet is still broken, but I'll fix that. The PNG works, so I will just add a workaround that changes the SVG to PNG extension in the HTML output

**Comment by rikhuijzer** [comment]
Everything seems to work again. Thanks a lot for the help @lazarusA!

**Comment by lazarusA** [comment]
Screenshot 2024-08-19 at 15 33 55

this one also looks off. I will take a look later.

**Comment by rikhuijzer** [comment]
> Screenshot 2024-08-19 at 15 33 55
> 
> this one also looks off. I will take a look later.

Yep same for me. Probably same problem :( It works in the PDF

**Comment by lazarusA** [comment]
yes, we should change also output to `png`.

**Comment by rikhuijzer** [comment]
> yes, we should change also output to `png`.

And maybe a Makie bug report? What do you think?

**Pull request merged**
