### PR TITLE
Fix broken link to makie docs

### LINKED ISSUE #82: Chapter 7 Link broken to Makie Docs
There is a link broken in Chapter 7 `datavisMakie.md`:

In the "See Makie’s documentation for more." It redirects to http://makie.juliaplots.org/stable/backends_and_output.html#Backends-and-Output which is broken.

cc @lazarusA

### PR DESCRIPTION
**Pull request by lazarusA**
this fixes issue https://github.com/JuliaDataScience/JuliaDataScience/issues/82

Closes #82.

### CODE REVIEW

**Review by rikhuijzer — APPROVED** [review]

**Comment by rikhuijzer** [comment]
I've changed the text so that the issue got linked. For details, see https://huijzer.xyz/posts/github-gitlab-commands-cheatsheet/.

**Comment by storopoli** [comment]
Aren’t we better linking to a static thing like dev or stable instead of a specific version?

**Comment by rikhuijzer** [comment]
> Aren’t we better linking to a static thing like dev or stable instead of a specific version?

It is quite stable now, isn't it? Dev could also become outdated because they change something upstream. Now, it refers at least to what we expect.

**Comment by storopoli** [comment]
The link is hard coded to version 0.15.1 can’t we do stable instead?

**Comment by lazarusA** [comment]
no, Julius is looking into it, it seems there is a problem with the links, all internal ones are relative which is not good. For now, this will work. In the mean time I will keep an eye on it.

**Comment by storopoli** [comment]
Ok so I will unclose the issue

**Pull request merged**
