### PR TITLE
Format trailing whitespace

### PR DESCRIPTION
**Pull request by rikhuijzer**
I've tried to do it via JuliaFormatter.jl. Unfortunately, that one is too quite aggressive. For now, I'll wait on https://github.com/domluna/JuliaFormatter.jl/pull/470.

The plan is to add a CI check for trailing whitespaces and other minor things.

### CODE REVIEW

**Comment by storopoli** [comment]
Great I also subscribed to the https://github.com/domluna/JuliaFormatter.jl/pull/470 which I will use extensively in the future.

**Comment by domluna** [comment]
@rikhuijzer what part was too aggresive?

**Comment by rikhuijzer** [comment]
> @rikhuijzer what part was too aggresive?

Hey, @domluna, thank your for your interest. I couldn't figure out how to set JuliaFormatter.jl to only fix trailing whitespace and, let's say, spaces in keyword arguments. Whatever I tried, the formatter was changing all kinds of things like putting things on newlines etc. Do you want me to open an issue at your repo?

**Comment by domluna** [comment]
oh i see, the PR you linked will fix most of that but there will still be cases that will be reformatted, for example

```
function foo()
   body   end
```

->

```
function foo()
    body
end
```

**Comment by rikhuijzer** [comment]
> oh i see, the PR you linked will fix most of that but there will still be cases that will be reformatted, for example
> 
> ```
> function foo()
>    body   end
> ```
> 
> ->
> 
> ```
> function foo()
>     body
> end
> ```

That sounds very reasonable :+1:

**Pull request closed without merging**
