### PR TITLE
Fix pipe alignment in front cover

### PR DESCRIPTION
**Pull request by lazarusA**
this should fix some alignment issues regarding the pipes. Additionally, I did a print for the previous one and the lack of grid lines makes the whole cover a little bit dull.

### CODE REVIEW

**Comment by lazarusA** [comment]
now it looks like this: 

test_front

**Review by rikhuijzer — APPROVED** [review]

**Comment by storopoli** [comment]
Why the grids? I've removed them since they do add unwanted complexity for the cover and steers the eyes away from the images.

Also the pipe from the 1st to 2nd row should be more to the right.

**Comment by lazarusA** [comment]
>  1st to 2nd row should be more to the right.
@storopoli you mean like in the centre? And without the grids I don't like it, it looks too empty. Do a print of both, so maybe you will see what I mean.

**Comment by lazarusA** [comment]
Like this? (grid lines more opaque, I think they should be there... @rikhuijzer ?)
test_front

**Comment by storopoli** [comment]
But in empty images? like in `fig[1, 2]` and `fig[2, 3]`

**Comment by storopoli** [comment]
I still think they should go. It's a cover not a formal "plot"  where you need them

**Comment by rikhuijzer** [comment]
I'm with @lazarusA here. Without, it looks a bit too empty even on thumbnail sizes.

**Comment by lazarusA** [comment]
@rikhuijzer wait... revert the merge please.

**Pull request merged**
