### PR TITLE
Up cheat sheets makie

### PR DESCRIPTION
**Pull request by lazarusA**
Could some one please help me here. The two new scripts (now we will upload also the code 😄) generate new cheat sheets for CairoMakie and GLMakie. I will be updating the whole chapter, I really don't like anymore, but I would like to have these ones already there. So, @rikhuijzer or @storopoli could either of you call the new functions at the bottom of this [file](https://github.com/JuliaDataScience/JuliaDataScience/blob/main/contents/data_vis_makie_attributes.md) and check that it works. `fig:cheat_sheet_cairomakie and fig:cheat_sheet_glmakie.`

cheatsheet_cairo

cheatsheet_glmakie

### CODE REVIEW

**Comment by lazarusA** [comment]
I'm on in 😄 . I will fix it.

**Comment by storopoli** [comment]
I am pushing a fix :) and I also did a formatting

**Comment by lazarusA** [comment]
Ahh, nice. In this case we want to call the plotting functions without showing the code and just the output image.

**Review by storopoli — APPROVED** [review]

**Comment by rikhuijzer** [comment]
These cheat sheets are amazing!

**Pull request merged**
