### PR TITLE
Add front cover to homepage

### PR DESCRIPTION
**Pull request by rikhuijzer**
@lazarusA, I've moved your code into the package and made some minor changes to get it working.

### CODE REVIEW

**Comment by rikhuijzer** [comment]
> Nice `devcontainers` are awesome

I've added it because `GLMakie` doesn't work on NixOS :\

**Comment by lazarusA** [comment]
Ok. I really don't like this one 🥲(it does not look good enough), so I would work a little bit more in the front cover, and update that image ASAP.

**Comment by rikhuijzer** [comment]
> Ok. I really don't like this one smiling_face_with_tear(it does not look good enough), so I would work a little bit more in the front cover, and update that image ASAP.

Okay. I've now hidden the image from the front page. Is it then okay to merge?

**Review by lazarusA — APPROVED** [review]
Nice, let's have in the main branch.

**Pull request merged**
