### PR TITLE
Simplify a sentence

### PR DESCRIPTION
**Pull request by pitmonticone**
Proposed simplification of the form of a question.

### CODE REVIEW

**Comment by rikhuijzer** [comment]
Wow. That's a poor sentence that you've spotted :+1:

**Comment by pitmonticone** [comment]
Yep, still not perfect. I'm sure it'll be improved after the completion and final review of the chapter. 

Thank you very much for making this resource publicly available!

**Comment by rikhuijzer** [comment]
> Thank you very much for making this resource publicly available!

Thank you! Happy to hear that you like it

cc: @lazarusA @storopoli

**Comment by storopoli** [comment]
Thanks!

**Pull request merged**
