### PR TITLE
Improve section numbering

### PR DESCRIPTION
**Pull request by Mo-Gul**
For a discussion see issue #221 that it is beneficial to have unnumbered sections when there are no other sections on that level, i.e. that there is no other "section x.2".

There is only the instance

https://github.com/JuliaDataScience/JuliaDataScience/blob/2c750e092b7aa932cf10d7fc12f1d0f7ba7ae909/contents/julia_basics.md#L671

which cannot be made unnumbered, because it is referenced at

https://github.com/JuliaDataScience/JuliaDataScience/blob/2c750e092b7aa932cf10d7fc12f1d0f7ba7ae909/contents/dataframes_performance.md#L9

My suggestion is to bring this one level up, i.e.

```diff
- #### Functions with a bang `!` {#sec:function_bang}
+ ### Functions with a bang `!` {#sec:function_bang}
```

I think that also fits to the previous section header where I (with my current n00bie understanding) don't see the "bang operator" fitting in.

Do you agree? If yes, I would prepare another commit. Otherwise you can merge the PR directly.

### CODE REVIEW

**Comment by rikhuijzer** [comment]
@Mo-Gul, if you go to the "Files changed" tab, you can accept the suggestions in one batch. Once that is done, I'll merge.

**Review by Mo-Gul — COMMENTED** [review]
I can't "approve" the PR, because I don't have the rights to do so. So I can "only" *comment* that the PR is good to go for me.

**Comment by rikhuijzer** [comment]
Sorry, I meant to say "commit" the suggestions in a batch.

**Comment by rikhuijzer** [comment]
Click the "Add suggestion to batch" to each suggestion you agree with and when you done click in the top on "commit" or something similar.

**Comment by Mo-Gul** [comment]
Sorry, but I can't do any more than I have done.

To my understanding the point you are mentioning is only available for *suggestions* to commits. But here we only have *commits*, so there is nothing to apply ...

**Comment by rikhuijzer** [comment]
> Sorry, but I can't do any more than I have done.
> 
> To my understanding the point you are mentioning is only available for _suggestions_ to commits. But here we only have _commits_, so there is nothing to apply ...

Sorry! This was completely my bad! I had comments still on "pending" so it looked like I suggested them but they weren't

**Comment by rikhuijzer** [comment]
I could click the button now myself. I'll make sure that this gets merged.

Thanks again

**Pull request merged**
