### PR TITLE
Update why_julia.md

### LINKED ISSUE #146: inversion judea and noam
in the file why_julia.md, line 250, there is an inversion between Judea and Noam

> That was not what `judea` as a `Linguist` type would say to `noam`, a `ComputerScientist` type.

Judea is the computer scientist and Noam the linguist. Moreover according to the line before it is Noam who speak to Judea, so I guess the line should be: 

> That was not what `noam` as a `Linguist` type would say to `judea`, a `ComputerScientist` type.

### PR DESCRIPTION
**Pull request by storopoli**
Closes #146.

### CODE REVIEW

**Comment by storopoli** [comment]
Hang on this needs a more profound review

**Comment by storopoli** [comment]
@rikhuijzer I've simplified the multiple dispatch part and removed the whole Judea and Noam example. What you think?

**Review by rikhuijzer — APPROVED** [review]
In Dutch, we say "schrijven is schrappen" (writing is deleting), so I approve very much of this PR.

**Comment by storopoli** [comment]
> EDIT: Upon re-read, I do see some other things that we might improve in this section, but we can leave that for another PR.

Be my guest the moment is now. Since you are citing dutch, I will cite Elvis: "It is now or never..."

**Comment by rikhuijzer** [comment]
This branch came from an old point in `main` and that's why CI is not running (https://github.com/JuliaDataScience/JuliaDataScience/network). If you want CI, merge main. Otherwise, feel free to merge without waiting for the requirements to be met.

**Pull request merged**
