### PR TITLE
Add full cover

### PR DESCRIPTION
**Pull request by rikhuijzer**
This PR add code to generate the full cover. See https://github.com/JuliaDataScience/JuliaDataScience/issues/17#issuecomment-927185934 for more information about the dimensions.

I don't consider the cover done and perfect now. It is meant as a place where we can start discussing the appearance.

# Preview

image

**EDIT:** This wasn't working in Amazon. It was turned into 

image

So, instead using the Amazon cover editor:

image

which is turned into

image

### CODE REVIEW

**Review by storopoli — APPROVED** [review]
Wow!! You've included our favicon in the spine!!!!

**Comment by lazarusA** [comment]
I must say, that now that I see it again.. I do like those scatter points in 3d with colors and everything.... and then probably it will look even better with the volume plot at the top... which is only available via GLMakie. Nice Job @rikhuijzer, it indeed looks great already.

**Comment by rikhuijzer** [comment]
@storopoli can you review this again? I've not included `cover.jl`, but still add the file to have a backup of the code in Git.

**Comment by cormullion** [comment]
_unsolicited suggestion for tweaking cover design_

Screenshot 2021-10-05 at 10 07 20

**Comment by storopoli** [comment]
😂 Amazing we were debating whether to ask for your suggestion. @lazarusA and @rikhuijzer what you think? Also @cormullion please speak freely about the cover. We really value your opinion!

**Comment by rikhuijzer** [comment]
haha yes awesome. Something is still off with the font, I think. But the placing of the text is much better indeed

**Comment by lazarusA** [comment]
@cormullion nice suggestion. if you have a different idea for the cover, we will be happy to hear about it.

**Comment by rikhuijzer** [comment]
Okay, Makie.jl isn't the best tool for the job, but I think it is better now:

image

@lazarusA @storopoli let's merge? We can fine tune it later

**Comment by lazarusA** [comment]
yes.

**Comment by cormullion** [comment]
I'm a fan of Barlow - open source, lots of good heavy weights for titles etc... 

It's useful to check out the idea by viewing the file as a thumbnail. If it works at that size it's probably a good design...

Screenshot 2021-10-05 at 11 15 10

**Comment by rikhuijzer** [comment]
This PR is starting more and more to suffer from scope creep. I think that the current PR is a strict improvement over the previous state, so I'll merge.

The implementation of the nice suggestions by cormulion can be further discussed at https://github.com/JuliaDataScience/JuliaDataScience/issues/151.

**Pull request merged**
